/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package PantallasAdmin;

import control.ControlRenta;
import dto.BicicletaDTO;
import dto.RentaDTO;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author PC Gamer
 */
public class PagarRenta extends javax.swing.JDialog {

    private RentaDTO rentaDto;
    private ControlRenta controlRenta;
    private float total;
    private int seleccionado;
    private JFrame main;
    private BicicletaDTO biciCompra;
    
    /**
     * Creates new form PagarRenta
     */
    public PagarRenta(java.awt.Frame parent, boolean modal, RentaDTO rentaDto, float total,BicicletaDTO bici) {
        super(parent, modal);
        initComponents();
        this.rentaDto = rentaDto;
        this.controlRenta = new ControlRenta();
        seleccionado=0;
        this.total=total;
        
        this.main=(JFrame) parent;
        
        this.setLocationRelativeTo(null);
        
        txtTotal.setText(total+"$");
        
        this.biciCompra=bici;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelRound3 = new Utileria.PanelRound();
        panelRound5 = new Utileria.PanelRound();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtTotal = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnEfectivo = new javax.swing.JButton();
        btnTarjeta = new javax.swing.JButton();
        btnPagar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        panelRound3.setBackground(new java.awt.Color(255, 255, 255));
        panelRound3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelRound5.setBackground(new java.awt.Color(230, 230, 230));
        panelRound5.setRoundBottomLeft(50);
        panelRound5.setRoundBottomRight(50);
        panelRound5.setRoundTopLeft(50);
        panelRound5.setRoundTopRight(50);
        panelRound5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8.setBackground(new java.awt.Color(0, 0, 0));
        jLabel8.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 0));
        jLabel8.setText("Metodos:");
        panelRound5.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, -1, -1));

        jLabel10.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel10.setText("Total:");
        panelRound5.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 140, -1, -1));

        txtTotal.setEditable(false);
        txtTotal.setBackground(new java.awt.Color(250, 250, 250));
        txtTotal.setEnabled(false);
        txtTotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTotalActionPerformed(evt);
            }
        });
        panelRound5.add(txtTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 180, 244, -1));

        jLabel1.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("En efectivo");
        panelRound5.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 220, -1, -1));

        jLabel2.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Tarjeta");
        panelRound5.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, -1, -1));

        btnEfectivo.setBackground(new java.awt.Color(180, 211, 178));
        btnEfectivo.setForeground(new java.awt.Color(0, 0, 0));
        btnEfectivo.setText("Seleccionar");
        btnEfectivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEfectivoActionPerformed(evt);
            }
        });
        panelRound5.add(btnEfectivo, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 250, 360, 50));

        btnTarjeta.setBackground(new java.awt.Color(173, 216, 230));
        btnTarjeta.setForeground(new java.awt.Color(0, 0, 0));
        btnTarjeta.setText("Seleccionar");
        btnTarjeta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTarjetaActionPerformed(evt);
            }
        });
        panelRound5.add(btnTarjeta, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, 360, 50));

        btnPagar.setText("Pagar");
        btnPagar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPagarActionPerformed(evt);
            }
        });
        panelRound5.add(btnPagar, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 240, -1, -1));

        btnCancelar.setBackground(new java.awt.Color(255, 105, 97));
        btnCancelar.setForeground(new java.awt.Color(0, 0, 0));
        btnCancelar.setText("Cancelar");
        panelRound5.add(btnCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 400, -1, -1));

        panelRound3.add(panelRound5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 800, 450));

        jPanel2.setBackground(new java.awt.Color(250, 210, 105));
        jPanel2.setForeground(new java.awt.Color(255, 138, 0));

        jLabel12.setBackground(new java.awt.Color(0, 0, 0));
        jLabel12.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(250, 250, 250));
        jLabel12.setText("Metodo de pago");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel12)
                .addContainerGap(652, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel12)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        panelRound3.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 850, 60));

        jButton4.setText("jButton1");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        panelRound3.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 4, 50, 50));

        jButton1.setText("jButton1");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        panelRound3.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 0, 70, 60));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelRound3, javax.swing.GroupLayout.PREFERRED_SIZE, 850, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelRound3, javax.swing.GroupLayout.PREFERRED_SIZE, 550, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void txtTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTotalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTotalActionPerformed

    private void btnPagarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPagarActionPerformed
        if(biciCompra==null){
            rentaDto.setCosto(total);
            java.util.Date fechaActualUtil = new java.util.Date(System.currentTimeMillis());
            java.sql.Date fechaActualSql = new java.sql.Date(fechaActualUtil.getTime());
            rentaDto.setFecha(fechaActualSql);
            if(seleccionado!=0){
            if(seleccionado==1){
                rentaDto.setMetodoPago("Tarjeta");
                PagarConTarjeta pagar=new PagarConTarjeta(main,rentaDto.getEmpleado(),rentaDto);
                PantallaMenu p=(PantallaMenu) main;
                p.showPanel(pagar);
                this.dispose();
            }else{
                rentaDto.setMetodoPago("Efectivo");
                PagarConEfectivo pagar=new PagarConEfectivo(main,rentaDto.getEmpleado(),rentaDto);
                PantallaMenu p=(PantallaMenu) main;
                p.showPanel(pagar);
                this.dispose();
            }
            }else{
                JOptionPane.showMessageDialog(this, "No has seleccionado ninguna forma de pago", 
                                          "Advertencia", JOptionPane.WARNING_MESSAGE);
            }
        }
            if(seleccionado!=0){
                if(seleccionado==1){
                    PagarConTarjeta pagar=new PagarConTarjeta(main,rentaDto.getEmpleado(),rentaDto);
                    PantallaMenu p=(PantallaMenu) main;
                    p.showPanel(pagar);
                    this.dispose();
                }else{
                    rentaDto.setMetodoPago("Efectivo");
                    PagarConEfectivo pagar=new PagarConEfectivo(main,rentaDto.getEmpleado(),rentaDto);
                    PantallaMenu p=(PantallaMenu) main;
                    p.showPanel(pagar);
                    this.dispose();
                }
            }
    }//GEN-LAST:event_btnPagarActionPerformed

    private void btnTarjetaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTarjetaActionPerformed
        // TODO add your handling code here:
        seleccionado = 1;
    }//GEN-LAST:event_btnTarjetaActionPerformed
   
    private void btnEfectivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEfectivoActionPerformed
        // TODO add your handling code here:
        seleccionado = 2;
    }//GEN-LAST:event_btnEfectivoActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnEfectivo;
    private javax.swing.JButton btnPagar;
    private javax.swing.JButton btnTarjeta;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel2;
    private Utileria.PanelRound panelRound3;
    private Utileria.PanelRound panelRound5;
    private javax.swing.JTextField txtTotal;
    // End of variables declaration//GEN-END:variables
}
