/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package PantallasAdmin;

import javax.swing.JFrame;
import javax.swing.JPanel;

/**
 *
 * @author PC Gamer
 */
public class SeleccionarBicicleta extends javax.swing.JDialog {
    
    private CompraRentaBicis c;
    private Integer idBicicleta;
    
    /**
     * Creates new form SeleccionarBicicleta
     */
    public SeleccionarBicicleta(java.awt.Frame parent, boolean modal,JFrame p) {
        super(parent, modal);
        initComponents();
        this.setLocationRelativeTo(null);
        c = new CompraRentaBicis(p,2,null);
        showPanel(c);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel12 = new javax.swing.JPanel();
        btnCancelar = new javax.swing.JButton();
        btnAceptar = new javax.swing.JButton();
        dashBoard = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel12.setBackground(new java.awt.Color(250, 250, 250));
        jPanel12.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnCancelar.setBackground(new java.awt.Color(255, 174, 105));
        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });
        jPanel12.add(btnCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 590, 110, 30));

        btnAceptar.setBackground(new java.awt.Color(255, 174, 105));
        btnAceptar.setText("Aceptar");
        btnAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAceptarActionPerformed(evt);
            }
        });
        jPanel12.add(btnAceptar, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 590, 120, 30));

        dashBoard.setPreferredSize(new java.awt.Dimension(850, 550));

        javax.swing.GroupLayout dashBoardLayout = new javax.swing.GroupLayout(dashBoard);
        dashBoard.setLayout(dashBoardLayout);
        dashBoardLayout.setHorizontalGroup(
            dashBoardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 850, Short.MAX_VALUE)
        );
        dashBoardLayout.setVerticalGroup(
            dashBoardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 550, Short.MAX_VALUE)
        );

        jPanel12.add(dashBoard, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 850, 550));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel12, javax.swing.GroupLayout.DEFAULT_SIZE, 880, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel12, javax.swing.GroupLayout.DEFAULT_SIZE, 636, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        // TODO add your handling code here:
        
        this.dispose();
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAceptarActionPerformed
        // TODO add your handling code here:
        if(idBicicleta!=null){
            System.out.println("Error: no se ha difinido la bicicleta");
        } else{
            idBicicleta=c.getIdBicicleta();
            this.dispose();
        }
    }//GEN-LAST:event_btnAceptarActionPerformed

    private void showPanel(JPanel p){
        p.setSize(850, 550);
        p.setLocation(0, 0);
        dashBoard.removeAll();
        dashBoard.add(p, new org.netbeans.lib.awtextra.AbsoluteConstraints(0,0,-1,-1));
        dashBoard.revalidate();
        dashBoard.repaint();
    }

    public Integer getIdBicicleta() {
        return idBicicleta;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAceptar;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JPanel dashBoard;
    private javax.swing.JPanel jPanel12;
    // End of variables declaration//GEN-END:variables
}
